In [1]:
import numpy as np
A = np.array([[2,-1],[0,3]])
B = np.array([[1,2],[-3,4]])

#For question 1(a)
print(A+B)

[[ 3  1]
 [-3  7]]


In [2]:
print(3*A-2*B)

[[ 4 -7]
 [ 6  1]]


In [3]:
print( A @ B)

[[ 5  0]
 [-9 12]]


In [4]:
det = round(np.linalg.det(A),2)
print(f"The determinant of matrix A is: {det}")
print()
if(not det==0):
    print("Inverse of matrix A exists.")
    inverse = np.linalg.inv(A)
    print("The inverse of the matrix A is:")
    print(inverse)
else:
    print("Inverse of matrix A doesn't exist.")

The determinant of matrix A is: 6.0

Inverse of matrix A exists.
The inverse of the matrix A is:
[[0.5        0.16666667]
 [0.         0.33333333]]


In [5]:
C = np.array([[4,1],[-2,1]])
egval,egvec = np.linalg.eig(A)
print(f"The eigen values of matrix A are: {egval}")
print()
print(f"The eigen vectors of matrix A are: {egvec}")

The eigen values of matrix A are: [2. 3.]

The eigen vectors of matrix A are: [[ 1.         -0.70710678]
 [ 0.          0.70710678]]


In [ ]:

F = np.array([[4,1.5,100],[6,2.0,150]])
Pr = np.array([[20,30]])
F = np.column_stack([np.ones(F.shape[0]), F])
B = ((np.linalg.inv(F.T @ F) @ F.T) @ Pr)
X = np.array([[1,8,3.0,200]])
price = np.linalg.det(X @ B)
print(f"The price of the house X3 is: {price}")

LinAlgError: Singular matrix